### ISSUE TITLE
LongPress show whiteItem which you pressed in iPhone7

### ISSUE THREAD

**Issue by ZYVIP** [lxcid/LXReorderableCollectionViewFlowLayout#107]
LongPress show whiteItem which you pressed in iPhone7.Please give me an advise,thank you

**Comment by ZYVIP** [comment]
![7s](https://cloud.githubusercontent.com/assets/20380063/18947628/7d73f6e8-8666-11e6-89d5-67ca58f89d6e.gif)

**Comment by ZYVIP** [comment]
原因找到了，snapshotViewAfterScreenUpdates这个方法在iPhone7和7P上面运行时是无效的

**Comment by KelaKing** [comment]
@ZYVIP 
是真机上也有问题，还是只有模拟器有问题？
Is iPhone have the problem, or only with the simulator?
