### ISSUE TITLE
Compilation error in version 0.2.0

### ISSUE THREAD

**Issue by siggb** [lxcid/LXReorderableCollectionViewFlowLayout#115]
Hi there! I've just got updated version of LXReorderableCollectionViewFlowLayout and find out that project won't compile anymore.

Xcode says:
> Cannot create __weak reference because the current deployment target does not support weak references

Screenshots:
![screen shot 2017-05-19 at 15 44 29](https://cloud.githubusercontent.com/assets/5582705/26248275/5c05c2de-3caa-11e7-8896-d1aa15c1b2af.png)

**Comment by lxcid** [comment]
Sorry, I believe I need to update the minimum deployment platform to iOS 5.0. Could you try `0.2.1` which I just released?

Reference commit f3486fe5f252be42bd8d93dd8434826ff6bccf3b

**Comment by siggb** [comment]
@lxcid Everything is OK. Thank you for the quick response.

**Comment by lxcid** [comment]
Awesome! Thanks for reporting!
